AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Push Service Stack


Mappings:

  LogMap:
    PapertrailLog:
      stage: "logs7.papertrailapp.com:23213"
      test: "logs7.papertrailapp.com:16637"
      prod: "logs7.papertrailapp.com:16747"

  FunctionName:
    UpdateTokenPushFunction:
      test: test-update-token-push
      stage: stage-update-token-push
      prod: prod-update-token-push
    UpdateTokenPushTargetGroup:
      test: test-update-token-push-tg
      stage: stage-update-token-push-tg
      prod: prod-update-token-push-tg
    UpdateFcmTokenPushFunction:
      test: test-update-fcm-token-push
      stage: stage-update-fcm-token-push
      prod: prod-update-fcm-token-push
    UpdateFcmTokenPushTargetGroup:
      test: test-update-fcm-token-push-tg
      stage: stage-update-fcm-token-push-tg
      prod: prod-update-fcm-token-push-tg
    TestPublishPushFunction:
      test: test-push
      stage: stage-push
      prod: prod-push
    SchedulerPushFunction:
      test: test-scheduler-push
      stage: stage-scheduler-push
      prod: prod-scheduler-push
    InternalHandleAsyncTaskFunction:
      test: test-internal-handler-async-task-push
      stage: stage-internal-handler-async-task-push
      prod: prod-internal-handler-async-task-push
    KinesisConsumerFunction:
      test: test-internal-handler-stream-push
      stage: stage-internal-handler-stream-push
      prod: prod-internal-handler-stream-push

  TableName:
    FcmTokenTable:
      test: test-Push-FCMTokenTable
      stage: stage-Push-FCMTokenTable
      prod: prod-Push-FCMTokenTable
    TokenTable:
      test: test-Push-TokenTable
      stage: stage-Push-TokenTable
      prod: prod-Push-TokenTable
    AlreadySentPush:
      test: test-Push-AlreadySentPush
      stage: stage-Push-AlreadySentPush
      prod: prod-Push-AlreadySentPush

  SQSName:
    PushTaskSqsQueue:
      test: test-push-task-queue-push
      stage: stage-push-task-queue-push
      prod: prod-push-task-queue-push
    PushTaskSqsDeadQueue:
      test: test-push-task-dead-queue-push
      stage: stage-push-task-dead-queue-push
      prod: prod-push-task-dead-queue-push

Parameters:
  Env:
    Type: String
    Default: stage
    AllowedValues:
      - test
      - stage
      - prod
    Description: Env name

Globals:
    Function:
        Timeout: 300
        MemorySize: 512
        Runtime: go1.x
        Environment:
          Variables:
            ENV: !Ref Env
            PAPERTRAIL_LOG_ADDRESS: !FindInMap [LogMap, PapertrailLog, !Ref Env]
            COMMON_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, CommonEventStreamExportName] ]
            DELIVERY_STREAM:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, DeliveryStreamExportName] ]
            FCM_TOKEN_TABLE_NAME: !FindInMap [TableName, FcmTokenTable, !Ref Env]
            ALREADY_SENT_PUSH_TABLE_NAME: !FindInMap [TableName, AlreadySentPush, !Ref Env]
            INTERNAL_AUTH_FUNCTION_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalGetUserIdFunctionExport] ]
            READY_FOR_PUSH_FUNCTION_NAME:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, RedyForPushFunctionExport] ]
            PUSH_TASK_QUEUE: !Ref PushTaskSqsQueue
        Tags:
          Company: Ringoid
          Service: push
          Environment: !Ref Env

Resources:

  TestPublishPushFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, TestPublishPushFunction, !Ref Env]
      Handler: publish
      CodeUri: ./publish.zip
      Description: Test publish function
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonSNSFullAccess
        - AWSLambdaFullAccess
        - SecretsManagerReadWrite

  SchedulerPushFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, SchedulerPushFunction, !Ref Env]
      Handler: scheduler
      CodeUri: ./scheduler.zip
      Description: Scheduler push function
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaFullAccess
        - AmazonSQSFullAccess
        - AmazonKinesisFullAccess
        - AmazonKinesisFirehoseFullAccess
        - SecretsManagerReadWrite

  ScheduledSchedulerPushFunctionRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Scheduled SchedulerPushFunction rule
      ScheduleExpression: rate(20 minutes)
      State: ENABLED
      Name: !Join [ "-", [ !Ref Env, schedule_push_function_rule] ]
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - SchedulerPushFunction
              - Arn
          Id: ScheduledSchedulerPushFunctionRuleId

  PermissionForEventsToInvokeSchedulerPushFunction:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SchedulerPushFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - ScheduledSchedulerPushFunctionRule
          - Arn

  UpdateFcmTokenPushFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, UpdateFcmTokenPushFunction, !Ref Env]
      Handler: update_fcm_token
      CodeUri: ./update_fcm_token.zip
      Description: Update FCM device token function
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonSNSFullAccess
        - AWSLambdaFullAccess
        - SecretsManagerReadWrite

  UpdateFcmTokenPushTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, UpdateFcmTokenPushTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt UpdateFcmTokenPushFunction.Arn
      TargetLambdaFunctionName: !Ref UpdateFcmTokenPushFunction

  UpdateFcmTokenPushListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt UpdateFcmTokenPushTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/push/update_fcm_token"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 503

  UpdateTokenPushFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, UpdateTokenPushFunction, !Ref Env]
      Handler: update
      CodeUri: ./update.zip
      Description: Update device token function
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonSNSFullAccess
        - AWSLambdaFullAccess
        - SecretsManagerReadWrite

  UpdateTokenPushTargetGroup:
    Type: Custom::CreateTargetGroup
    Properties:
      ServiceToken:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, CustomResourceFunctionExport] ]
      CustomName: !FindInMap [FunctionName, UpdateTokenPushTargetGroup, !Ref Env]
      CustomTargetsId: !GetAtt UpdateTokenPushFunction.Arn
      TargetLambdaFunctionName: !Ref UpdateTokenPushFunction

  UpdateTokenPushListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !GetAtt UpdateTokenPushTargetGroup.TargetGroupArn
      Conditions:
        - Field: path-pattern
          Values:
            - "/push/update_token"
      ListenerArn:
        Fn::ImportValue:
          !Join [ "-", [ !Ref Env, ListenerArnExport] ]
      Priority: 501

  InternalHandleAsyncTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, InternalHandleAsyncTaskFunction, !Ref Env]
      Handler: internal_handle_task
      CodeUri: ./internal_handle_task.zip
      Description: Handle async task (push) from the queue
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonSNSFullAccess
        - AmazonKinesisFirehoseFullAccess
        - AmazonKinesisFullAccess
        - SecretsManagerReadWrite
      Events:
        StartEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
                - PushTaskSqsQueue
                - Arn
            BatchSize: 10

  PushTaskSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !FindInMap [SQSName, PushTaskSqsQueue, !Ref Env]
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - PushTaskSqsDeadQueue
            - Arn
        maxReceiveCount: 3

  PushTaskSqsDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !FindInMap [SQSName, PushTaskSqsDeadQueue, !Ref Env]

  KinesisConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !FindInMap [FunctionName, KinesisConsumerFunction, !Ref Env]
      Handler: handle_stream
      CodeUri: ./handle_stream.zip
      Description: Consumer for Kinesis stream
      Policies:
        - AmazonKinesisFullAccess
        - AmazonDynamoDBFullAccess
        - AmazonSQSFullAccess
        - AmazonKinesisFirehoseFullAccess
        - SecretsManagerReadWrite
      Events:
        CommonEventStreamEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [ "-", [ !Ref Env, InternalEventStreamExport] ]
            StartingPosition: TRIM_HORIZON
            BatchSize: 1

  AlreadySentPush:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [TableName, AlreadySentPush, !Ref Env]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
      Tags:
        - Key: Company
          Value: Ringoid
        - Key: Service
          Value: push
        - Key: Environment
          Value: !Ref Env

  FcmTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [TableName, FcmTokenTable, !Ref Env]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S

      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH

      Tags:
        - Key: Company
          Value: Ringoid
        - Key: Service
          Value: push
        - Key: Environment
          Value: !Ref Env

  TokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [TableName, TokenTable, !Ref Env]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: device_token
          AttributeType: S
        -
          AttributeName: os
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: device_token
          KeyType: HASH
        -
          AttributeName: os
          KeyType: RANGE

      GlobalSecondaryIndexes:
        -
          IndexName: userIdGSI
          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Company
          Value: Ringoid
        - Key: Service
          Value: push
        - Key: Environment
          Value: !Ref Env
